#!/bin/bash
xset s off -dpms
while true; do
if [ -d $HOME/startpage ]; then
  cd $HOME/startpage
  git pull
  cd $HOME
  else
  cd $HOME
  git clone https://github.com/floorup1/startpage.git
fi
rm -rf $HOME/.config/chromium/*
rm -rf $HOME/.cache/chromium/*
rm -rf $HOME/Downloads/*
rm -rf $HOME/share/*
chromium --start-maximized 'file:///home/kiosk-user/startpage/start.html'
done
