- hosts: localhost
  ignore_errors: true
  tasks:
    - name: It's task 1
      ansible.builtin.shell: rm -rf ~/*txt

    - name: task2
      ansible.builtin.shell: mkdir -p 777 /home/kiosk-user/share

    - name: Install on Debian
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - samba
    
    - name: Insert a block after EOF
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [share]
          comment = share
          path = /home/kiosk-user/share
          browseable = yes
          guest ok = yes
          create mode = 0766
          writeable = yes
          force user = kiosk-user
