- hosts: localhost
  ignore_errors: true
  tasks:
    - name: It's task 1
      ansible.builtin.shell: rm -rf ~/*txt
    
    - name: task 2
      ansible.builtinshell: /home/kiosk-user/.config/openbox/autostart