- hosts: localhost
  ignore_errors: true
  tasks:

    - name: Insert a block after EOF
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [share]
          comment = share
          path = /home/kiosk-user/share
          browseable = yes
          guest ok = yes
          create mode = 0766
          writeable = yes
          force user = kiosk-user
