- hosts: localhost
  ignore_errors: true
  tasks:
    - name: It's task 1
      ansible.builtin.shell: rm -rf ~/*txt

    - name: task2
      ansible.builtin.shell: mkdir -p 777 /home/kiosk-user/share

    - name: Install on Debian
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - samba
    
    - name: Insert a block at the beginning of a file
      ansible.builtin.blockinfile:
        path: /home/kiosk-user/myfile.conf
        insertafter: EOF
        block: |
          This is the block to insert
          It goes at the start of
