- hosts: localhost
  ignore_errors: true
  tasks:
    - name: It's task 1
      ansible.builtin.shell: rm -rf ~/*txt

    - name: task2
      ansible.builtin.shell: mkdir -p 777 /home/kiosk-user/share

    - name: Install on Ubuntu
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - samba
