- hosts: localhost
  ignore_errors: true
  tasks:
    - name: It's task 1
      ansible.builtin.shell: echo "Шолом мир" >> ~/1.txt
      
    - name: It's task 2
      ansible.builtin.shell: yum search nasm yasm &>~/2.txt
