- hosts: localhost
  ignore_errors: true
  tasks:
    - name: It's task 1
      ansible.builtin.shell: rm -rf ~/1.txt ~/2.txt

    - name: ping 
      ansible.builtin.shell: ping -c 6 8.8.8.8 >> $HOME/3.txt

    - name: pingrunonce
      ansible.builtin.shell: ping -c 6 pikabu.ru >> $HOME/5.txt
      run_once: true